name : CI workflow

on:
  push:
    branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  build:
      runs-on: ubuntu-latest
      container: python:3.9-slim

 steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Hello from Action
      run: echo "GitHub Actions running 🎉"