name : CI workflow

on:
  push:
    branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  build:
      run-on: ubuntu-latest
      container: python:3.9-slim
      
steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run Python script
      run: echo "Hello from inside the GitHub Action!